### ISSUE TITLE
Deleting files in the the project's folder

### ISSUE THREAD

**Issue by kexoth** [afonsograca/fastlane-plugin-synx#1]
Hello @afonsograca 

I liked the idea behind your projects & as I can see it does the job as descriped.

But I don't know how it deleted all the files that were in my project's folder & referenced at the same level in Xcode, i.e. in the project's root.

![screen shot on 2016-08-12 at 21_37_42](https://cloud.githubusercontent.com/assets/883816/17635061/c455b3dc-60d5-11e6-92fa-5b585e390355.png)

How & why did this happens. Is there any convention that I need to follow. Is this a bug or a feature? 😄 

Thanks,
@kexoth

**Comment by afonsograca** [comment]
Hi @kexoth,

The idea of Synx is to establish the hierarchy relative to the Groups defined in Xcode.

If I understood correctly, you had these files in the Project's root, ran Synx and the files were deleted.

This should not happen, unless you pass `prune: true` to the method. Activating the _prune_ option removes source files and image resources that are not referenced by the the xcode project.

On the other hand, if previously you had these files in a Group, ran Synx and then moved them to the project's root, this would cause the files to appear as if they were deleted, because they are in another directory. Running Synx again should fix this.

Cheers
